#!/bin/bash

NETCDFLIB="-L/usr/local/netcdf-fortran/4.4.3/gnu4.8.5/lib64/ -lnetcdff"

NETCDFINC="-I/usr/local/netcdf-fortran/4.4.3/gnu4.8.5/include/"

CPP1="-cpp -O3 -ffpe-trap=zero -mcmodel=medium -traditional -DLinux -openmp"

gfortran $CPP1 param.f90 harmonic_regression.f90 write_harmonic_output.f90 harmonic_analysis.f90 -o result $NETCDFLIB $NETCDFINC

./result

rm result *.mod
